import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import { tasks } from '../db/schema';
import 'dotenv/config'


const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
});

const db = drizzle(pool);


const seedTasks: any[] = [
    {
        name: "Fix login bug",
        status: "OPEN",
        priority: "P1",
        assignee: "John Doe",
        createdAt: "2025-01-01",
        labels: ["bug"],
        description: "Users unable to login with correct credentials",
        comment: "Affecting 30% of users",
    },
    {
        name: "Add dark mode",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "Sarah Chen",
        createdAt: "2025-01-01",
        labels: ["feature"],
        description: "Implement dark mode across all pages",
        comment: "Design approved",
    },
    {
        name: "Update API docs",
        status: "CLOSED",
        priority: "P3",
        assignee: "Mike Brown",
        createdAt: "2025-01-02",
        labels: ["doc"],
        description: "Update documentation for v2 API",
        comment: "All endpoints documented",
    },
    {
        name: "Fix mobile nav",
        status: "OPEN",
        priority: "P1",
        assignee: "Emma Wilson",
        createdAt: "2025-01-02",
        labels: ["bug"],
        description: "Mobile navigation menu not responsive",
        comment: "iOS specific issue",
    },
    {
        name: "Add search feature",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "John Doe",
        createdAt: "2025-01-03",
        labels: ["feature"],
        description: "Implement global search",
        comment: "Using Elasticsearch",
    },
    {
        name: "Memory leak fix",
        status: "CLOSED",
        priority: "P1",
        assignee: "Sarah Chen",
        createdAt: "2025-01-03",
        labels: ["bug"],
        description: "Fix memory leak in dashboard",
        comment: "Optimized render cycle",
    },
    {
        name: "User guide update",
        status: "OPEN",
        priority: "P3",
        assignee: "Mike Brown",
        createdAt: "2025-01-04",
        labels: ["doc"],
        description: "Update user guide for new features",
        comment: "Include screenshots",
    },
    {
        name: "Password reset bug",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "Emma Wilson",
        createdAt: "2025-01-04",
        labels: ["bug"],
        description: "Password reset emails not sending",
        comment: "SMTP configuration issue",
    },
    {
        name: "Add analytics",
        status: "OPEN",
        priority: "P0",
        assignee: "John Doe",
        createdAt: "2025-01-05",
        labels: ["feature"],
        description: "Implement Google Analytics",
        comment: "GDPR compliance needed",
    },
    {
        name: "Fix data export",
        status: "CLOSED",
        priority: "P0",
        assignee: "Sarah Chen",
        createdAt: "2025-01-05",
        labels: ["bug"],
        description: "CSV export not working",
        comment: "Fixed encoding issue",
    },
    {
        name: "Add notifications",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "Mike Brown",
        createdAt: "2025-01-06",
        labels: ["feature"],
        description: "Implement push notifications",
        comment: "Using Firebase",
    },
    {
        name: "Update README",
        status: "CLOSED",
        priority: "P3",
        assignee: "Emma Wilson",
        createdAt: "2025-01-06",
        labels: ["doc"],
        description: "Update project README",
        comment: "Added setup guide",
    },
    {
        name: "Fix checkout bug",
        status: "OPEN",
        priority: "P1",
        assignee: "John Doe",
        createdAt: "2025-01-07",
        labels: ["bug"],
        description: "Payment processing error",
        comment: "Stripe integration issue",
    },
    {
        name: "Add user roles",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "Sarah Chen",
        createdAt: "2025-01-07",
        labels: ["feature"],
        description: "Implement role-based access",
        comment: "Admin and user roles",
    },
    {
        name: "Fix image upload",
        status: "CLOSED",
        priority: "P0",
        assignee: "Mike Brown",
        createdAt: "2025-01-08",
        labels: ["bug"],
        description: "Image upload not working",
        comment: "S3 config fixed",
    },
    {
        name: "Add rate limiting",
        status: "OPEN",
        priority: "P1",
        assignee: "Emma Wilson",
        createdAt: "2025-01-08",
        labels: ["feature"],
        description: "Implement API rate limiting",
        comment: "Using Redis",
    },
    {
        name: "Update security docs",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "John Doe",
        createdAt: "2025-01-09",
        labels: ["doc"],
        description: "Document security practices",
        comment: "Include auth fP3",
    },
    {
        name: "Fix sorting bug",
        status: "CLOSED",
        priority: "P3",
        assignee: "Sarah Chen",
        createdAt: "2025-01-09",
        labels: ["bug"],
        description: "Table sorting not working",
        comment: "Fixed comparator",
    },
    {
        name: "Add file preview",
        status: "OPEN",
        priority: "P0",
        assignee: "Mike Brown",
        createdAt: "2025-01-10",
        labels: ["feature"],
        description: "Add PDF preview feature",
        comment: "Using pdf.js",
    },
    {
        name: "Cache optimization",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "Emma Wilson",
        createdAt: "2025-01-10",
        labels: ["feature"],
        description: "Implement Redis caching",
        comment: "For API responses",
    },
    {
        name: "Fix toast messages",
        status: "OPEN",
        priority: "P3",
        assignee: "John Doe",
        createdAt: "2025-01-11",
        labels: ["bug"],
        description: "Toast notifications overlap",
        comment: "Z-index issue",
    },
    {
        name: "Add bulk actions",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "Sarah Chen",
        createdAt: "2025-01-11",
        labels: ["feature"],
        description: "Add bulk delete/update",
        comment: "For data table",
    },
    {
        name: "Update CI/CD docs",
        status: "CLOSED",
        priority: "P3",
        assignee: "Mike Brown",
        createdAt: "2025-01-12",
        labels: ["doc"],
        description: "Document deployment process",
        comment: "Added pipeline info",
    },
    {
        name: "Fix form validation",
        status: "OPEN",
        priority: "P0",
        assignee: "Emma Wilson",
        createdAt: "2025-01-12",
        labels: ["bug"],
        description: "Form validation not working",
        comment: "Mobile only issue",
    },
    {
        name: "Add SSO support",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "John Doe",
        createdAt: "2025-01-13",
        labels: ["feature"],
        description: "Implement SSO login",
        comment: "Using OAuth 2.0",
    },
    {
        name: "Fix date picker",
        status: "CLOSED",
        priority: "P0",
        assignee: "Sarah Chen",
        createdAt: "2025-01-13",
        labels: ["bug"],
        description: "Date picker format wrong",
        comment: "Fixed timezone issue",
    },
    {
        name: "Add file upload",
        status: "OPEN",
        priority: "P1",
        assignee: "Mike Brown",
        createdAt: "2025-01-14",
        labels: ["feature"],
        description: "Add drag-drop upload",
        comment: "With progress bar",
    },
    {
        name: "Update error docs",
        status: "IN_PROGRESS",
        priority: "P3",
        assignee: "Emma Wilson",
        createdAt: "2025-01-14",
        labels: ["doc"],
        description: "Document error codes",
        comment: "Include examples",
    },
    {
        name: "Fix search filter",
        status: "CLOSED",
        priority: "P0",
        assignee: "John Doe",
        createdAt: "2025-01-15",
        labels: ["bug"],
        description: "Search filters not applying",
        comment: "Fixed query params",
    },
    {
        name: "Add pagination",
        status: "OPEN",
        priority: "P0",
        assignee: "Sarah Chen",
        createdAt: "2025-01-15",
        labels: ["feature"],
        description: "Add infinite scroll",
        comment: "With virtual list",
    },
    {
        name: "Fix cache bug",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "Mike Brown",
        createdAt: "2025-01-16",
        labels: ["bug"],
        description: "Cache not invalidating",
        comment: "Redis key issue",
    },
    {
        name: "Add webhooks",
        status: "CLOSED",
        priority: "P1",
        assignee: "Emma Wilson",
        createdAt: "2025-01-16",
        labels: ["feature"],
        description: "Implement webhooks",
        comment: "With retry logic",
    },
    {
        name: "Update API docs",
        status: "OPEN",
        priority: "P3",
        assignee: "John Doe",
        createdAt: "2025-01-17",
        labels: ["doc"],
        description: "Update API documentation",
        comment: "New endpoints",
    },
    {
        name: "Fix dropdown bug",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "Sarah Chen",
        createdAt: "2025-01-17",
        labels: ["bug"],
        description: "Dropdown menu broken",
        comment: "CSS z-index issue",
    },
    {
        name: "Add audit logs",
        status: "CLOSED",
        priority: "P1",
        assignee: "Mike Brown",
        createdAt: "2025-01-18",
        labels: ["feature"],
        description: "Implement audit logging",
        comment: "Using Winston",
    },
    {
        name: "Fix print layout",
        status: "OPEN",
        priority: "P3",
        assignee: "Emma Wilson",
        createdAt: "2025-01-18",
        labels: ["bug"],
        description: "Print layout broken",
        comment: "CSS print media",
    },
    {
        name: "Add export feature",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "John Doe",
        createdAt: "2025-01-19",
        labels: ["feature"],
        description: "Add PDF export",
        comment: "Using puppeteer",
    },
    {
        name: "Update changelog",
        status: "CLOSED",
        priority: "P3",
        assignee: "Sarah Chen",
        createdAt: "2025-01-19",
        labels: ["doc"],
        description: "Update changelog for v2",
        comment: "All changes listed",
    },
    {
        name: "Fix session bug",
        status: "OPEN",
        priority: "P1",
        assignee: "Mike Brown",
        createdAt: "2025-01-20",
        labels: ["bug"],
        description: "Session not persisting",
        comment: "Redis connection",
    },
    {
        name: "Add comments",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "Emma Wilson",
        createdAt: "2025-01-20",
        labels: ["feature"],
        description: "Add comment system",
        comment: "With mentions",
    },
    {
        name: "Fix avatar upload",
        status: "CLOSED",
        priority: "P3",
        assignee: "John Doe",
        createdAt: "2025-01-21",
        labels: ["bug"],
        description: "Avatar upload fails",
        comment: "Image resize fixed",
    },
    {
        name: "Add dashboard",
        status: "OPEN",
        priority: "P1",
        assignee: "Sarah Chen",
        createdAt: "2025-01-21",
        labels: ["feature"],
        description: "Create analytics dashboard",
        comment: "With charts",
    },
    {
        name: "Update docs",
        status: "IN_PROGRESS",
        priority: "P3",
        assignee: "Mike Brown",
        createdAt: "2025-01-22",
        labels: ["doc"],
        description: "Update documentation",
        comment: "New features",
    },
    {
        name: "Fix chart bug",
        status: "CLOSED",
        priority: "P0",
        assignee: "Emma Wilson",
        createdAt: "2025-01-22",
        labels: ["bug"],
        description: "Charts not updating",
        comment: "React refresh",
    },
    {
        name: "Add keyboard shortcuts",
        status: "OPEN",
        priority: "P0",
        assignee: "John Doe",
        createdAt: "2025-01-23",
        labels: ["feature"],
        description: "Add keyboard navigation",
        comment: "With help modal",
    },
    {
        name: "Fix search bug",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "Sarah Chen",
        createdAt: "2025-01-23",
        labels: ["bug"],
        description: "Search not working",
        comment: "Query timeout",
    },
    {
        name: "Add theme support",
        status: "CLOSED",
        priority: "P0",
        assignee: "Mike Brown",
        createdAt: "2025-01-24",
        labels: ["feature"],
        description: "Add custom themes",
        comment: "With color picker",
    },
    {
        name: "Update help docs",
        status: "OPEN",
        priority: "P3",
        assignee: "Emma Wilson",
        createdAt: "2025-01-24",
        labels: ["doc"],
        description: "Update help center",
        comment: "New articles",
    },
    {
        name: "Fix tooltip bug",
        status: "IN_PROGRESS",
        priority: "P3",
        assignee: "John Doe",
        createdAt: "2025-01-25",
        labels: ["bug"],
        description: "Tooltips misaligned",
        comment: "Position calc",
    },
    {
        name: "Add backup system",
        status: "CLOSED",
        priority: "P1",
        assignee: "Sarah Chen",
        createdAt: "2025-01-25",
        labels: ["feature"],
        description: "Implement backups",
        comment: "Daily schedule",
    },
    {
        name: "Fix sorting issue",
        status: "OPEN",
        priority: "P0",
        assignee: "Mike Brown",
        createdAt: "2025-01-26",
        labels: ["bug"],
        description: "Table sorting wrong",
        comment: "Date comparison",
    },
    {
        name: "Add report builder",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "Emma Wilson",
        createdAt: "2025-01-26",
        labels: ["feature"],
        description: "Create report builder",
        comment: "With templates",
    },
    {
        name: "Update style guide",
        status: "CLOSED",
        priority: "P3",
        assignee: "John Doe",
        createdAt: "2025-01-27",
        labels: ["doc"],
        description: "Update style guide",
        comment: "New components",
    },
    {
        name: "Fix email bug",
        status: "OPEN",
        priority: "P1",
        assignee: "Sarah Chen",
        createdAt: "2025-01-27",
        labels: ["bug"],
        description: "Emails not sending",
        comment: "SMTP config",
    },
    {
        name: "Add data import",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "Mike Brown",
        createdAt: "2025-01-28",
        labels: ["feature"],
        description: "Add CSV import",
        comment: "With validation",
    },
    {
        name: "Fix carousel bug",
        status: "CLOSED",
        priority: "P3",
        assignee: "Emma Wilson",
        createdAt: "2025-01-28",
        labels: ["bug"],
        description: "Carousel stuck",
        comment: "Animation fix",
    },
    {
        name: "Add monitoring",
        status: "OPEN",
        priority: "P1",
        assignee: "John Doe",
        createdAt: "2025-01-29",
        labels: ["feature"],
        description: "Add system monitoring",
        comment: "Using Datadog",
    },
    {
        name: "Update tech docs",
        status: "IN_PROGRESS",
        priority: "P3",
        assignee: "Sarah Chen",
        createdAt: "2025-01-29",
        labels: ["doc"],
        description: "Update architecture docs",
        comment: "New diagrams",
    },
    {
        name: "Fix login button issue on the homepage",
        status: "OPEN",
        priority: "P0",
        assignee: "John Doe",
        comment: "",
        createdAt: "2025-01-10",
        labels: ["bug"],
        description:
            "Investigate and resolve the issue causing the login button on the homepage to not respond to user clicks. Ensure functionality is restored and tested across devices.",
    },
    {
        name: "Implement new payment gateway integration",
        status: "CLOSED",
        priority: "P2",
        assignee: "Jane Smith",
        createdAt: "2025-01-08",
        labels: ["feature"],
        comment: "",
        description:
            "Integrate the new payment gateway as per the provided API documentation. Validate the integration through test transactions and address any edge cases.",
    },
    {
        name: "Write documentation for new API endpoints",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "Alice Johnson",
        createdAt: "2025-01-12",
        labels: ["doc"],
        description:
            "Create comprehensive documentation for the newly added API endpoints, including usage examples, error codes, and expected responses.",
        comment: "",
    },
    {
        name: "Refactor code for search functionality",
        status: "OPEN",
        priority: "P0",
        assignee: "Mark Brown",
        createdAt: "2025-01-15",
        labels: ["bug", "feature"],
        description:
            "Refactor the existing search functionality to improve performance and maintainability. Address known bugs and optimize queries for large datasets.",
        comment: "",
    },
    {
        name: "Fix UI bug on the profile page",
        status: "CLOSED",
        priority: "P1",
        assignee: "Emily Clark",
        createdAt: "2025-01-05",
        labels: ["feature"],
        description:
            "Resolve the alignment and styling issues reported on the profile page. Ensure a consistent user experience across different screen sizes.",
        comment: "",
    },
    {
        name: "Prepare user guide for the new feature release",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "Chris Williams",
        createdAt: "2025-01-20",
        labels: ["doc", "bug"],
        description:
            "Draft a detailed user guide to accompany the new feature release, including screenshots, step-by-step instructions, and troubleshooting tips.",
        comment: "",
    },
    {
        name: "Design homepage for the new website layout",
        status: "OPEN",
        priority: "P2",
        assignee: "Sophia Moore",
        createdAt: "2025-01-22",
        labels: ["bug"],
        description:
            "Create a modern and responsive homepage design for the upcoming website layout update. Focus on usability and aesthetic appeal.",
        comment: "",
    },
    {
        name: "Update feature flags for version 2.0",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "David Taylor",
        createdAt: "2025-01-18",
        labels: ["feature", "doc"],
        description:
            "Modify the existing feature flags to align with the updates in version 2.0. Ensure compatibility and proper toggling during deployment.",
        comment: "",
    },
    {
        name: "Investigate crash issue on mobile app",
        status: "CLOSED",
        priority: "P0",
        assignee: "Laura Lee",
        createdAt: "2025-01-03",
        labels: ["bug"],
        description:
            "Analyze the root cause of the crash issue reported on the mobile app. Implement and test a robust fix to prevent recurrence.",
        comment: "",
    },
    {
        name: "Implement user authentication improvements",
        status: "OPEN",
        priority: "P1",
        assignee: "Michael Harris",
        createdAt: "2025-01-25",
        labels: ["doc", "feature"],
        description:
            "Enhance the user authentication process by introducing new security measures and improving usability. Update documentation accordingly.",
        comment: "",
    },
    {
        name: "Redesign settings page UI for better user experience",
        status: "IN_PROGRESS",
        priority: "P2",
        assignee: "Olivia Young",
        createdAt: "2025-01-28",
        labels: ["feature"],
        description:
            "Overhaul the settings page interface to improve navigation and accessibility. Conduct user testing to validate design changes.",
        comment: "",
    },
    {
        name: "Fix broken links in the help section",
        status: "CLOSED",
        priority: "P0",
        assignee: "James Walker",
        createdAt: "2025-01-07",
        labels: ["bug"],
        description:
            "Identify and correct all broken links within the help section. Ensure all links point to relevant and accurate resources.",
        comment: "",
    },
    {
        name: "Update changelog for version 1.5 release",
        status: "OPEN",
        priority: "P1",
        assignee: "Liam Gonzalez",
        createdAt: "2025-01-10",
        labels: ["doc"],
        description:
            "Compile and update the changelog for version 1.5, detailing all significant changes, improvements, and fixes.",
        comment: "",
    },
    {
        name: "Implement new search filters in product catalog",
        status: "IN_PROGRESS",
        priority: "P0",
        assignee: "Mia Allen",
        createdAt: "2025-01-30",
        labels: ["feature", "doc"],
        description:
            "Add advanced search filters to the product catalog to enhance user experience. Document filter options and usage scenarios.",
        comment: "",
    },
    {
        name: "Fix payment failure notification issue",
        status: "CLOSED",
        priority: "P2",
        assignee: "Ethan King",
        createdAt: "2025-01-02",
        labels: ["bug"],
        description:
            "Address the issue causing payment failure notifications to not display properly. Verify with test cases to ensure consistent behavior.",
        comment: "",
    },
    {
        name: "Create wireframes for new admin dashboard",
        status: "IN_PROGRESS",
        priority: "P1",
        assignee: "Avery Scott",
        createdAt: "2025-01-23",
        labels: ["doc"],
        description:
            "Design detailed wireframes for the upcoming admin dashboard, focusing on clarity, ease of use, and efficient data presentation.",
        comment: "",
    },
    {
        name: "Test user registration process on mobile app",
        status: "OPEN",
        priority: "P0",
        assignee: "Charlotte Martinez",
        createdAt: "2025-02-01",
        labels: ["feature"],
        description:
            "Thoroughly test the user registration fP3 on the mobile app. Identify and resolve any issues, ensuring a smooth onboarding experience.",
        comment: "",
    },
    {
        name: "Update privacy policy for GDPR compliance",
        status: "CLOSED",
        priority: "P1",
        assignee: "Elijah Moore",
        createdAt: "2025-01-04",
        labels: ["doc"],
        description:
            "Revise the privacy policy to ensure full compliance with GDPR regulations. P1light changes and communicate them effectively to users.",
        comment: "",
    },
    {
        name: "Fix UI glitch on the checkout page",
        status: "IN_PROGRESS",
        priority: "P2",
        assignee: "Amelia White",
        createdAt: "2025-01-26",
        labels: ["feature"],
        description:
            "Identify and fix the visual inconsistencies on the checkout page. Verify alignment and functionality across browsers.",
        comment: "",
    },
    {
        name: "Refactor user profile management code",
        status: "OPEN",
        priority: "P0",
        assignee: "Henry Harris",
        createdAt: "2025-01-29",
        labels: ["bug"],
        description:
            "Improve the structure and readability of the user profile management codebase. Address existing issues and ensure future scalability.",
        comment: "",
    },
];


const seedData = async () => {

    const existingTasks = await db.select().from(tasks);
    if (existingTasks.length !== 0) {
        console.log('Data already seeded');
        return;
    }

    try {
        for (const task of seedTasks) {
            await db.insert(tasks).values({
                name: task.name,
                status: task.status,
                priority: task.priority,
                assignee: task.assignee,
                comment: task.comment,
                createdAt: task.createdAt,
                labels: task.labels,
                description: task.description,
            });
        }
        console.log('Seeding CLOSED successfully!');
    } catch (error) {
        console.error('Error seeding data:', error);
    } finally {
        await pool.end();
    }
};

seedData();
